### ISSUE TITLE
Về hàm lượng giá cho game caro

### ISSUE THREAD

**Issue by cuong95nddev** [chanhbc/CoCaro#1]
Anh ơi em đang làm btl AI và tình cờ tham khảo được bài đăng của anh 
https://daynhauhoc.com/t/demo-game-co-caro-tren-microsoft-visual-studio-2013/13011

Em có một vài thắc mắc về việc tại sao phải chạy tiếp phần này khi gặp ô trống 
`for(int dem2 = 2; dem2 < 6 && crRow - dem2 >= 0; dem2++)
                        if (_Mang_O_Co[crRow - dem2, crColumn].Own == 1)
                        {
                            _SoQT2++;
                            break;
                        }
                        else if (_Mang_O_Co[crRow - dem2, crColumn].Own == 2)
                        {
                            _SoQD2++;
                        }
                        else 
                            break;
                    break;`
Cám ơn anh nhiều.
Anh có thể cho em mail để tiện liên lạc một số vấn đề được không ạ.

**Comment by chanhbc** [comment]
nó giúp cho máy có thể tính các trường hợp bỏ qua 1 ô trống đó, ví dụ  2 con cờ _ 1 ô trống _ 1 con cờ

**Comment by cuong95nddev** [comment]
Ủ vậy là mình phải chạy tiếp từ đó chứ sao lại quay về chạy từ 2 làm gì vậy ạ.
Anh có thể minh họa hình được không ạ.

**Comment by chanhbc** [comment]
Thực ra mình cũng không nhớ lắm. phải đọc lại mới hiểu được

**Comment by chanhbc** [comment]
Bạn có thể chỉ cho mình bạn đang nói ở đoạn nào được không? Bạn đang nói ở đoạn nào hàm nào để mình tìm được không, rất lâu rồi nên mình không nhớ được

**Comment by cuong95nddev** [comment]
![2017-03-11_174154](https://cloud.githubusercontent.com/assets/13380834/23825464/d22055f2-06bc-11e7-8ffa-2f2e885af519.png)
Đoạn này nè anh

**Comment by chanhbc** [comment]
chỗ đó mình nói rồi mà. giả sử nếu đang duyệt quân địch có 2 quân địch tiếp theo 2 quân địch là 1 ô trống nó vẫn tiếp tục kiểm tra trong trường hợp ô tiếp theo là quân địch(sau ô trống đó) thì nó cũng tính là 3 quân địch để chặn nếu không chặn quân địch đánh vô đó là được nước 4 => thua

**Comment by cuong95nddev** [comment]
Ok thank anh nhiều.

**Comment by chanhbc** [comment]
không có gì
